name: githubcicd
on: workflow_dispatch
# This workflow is triggered by a manual dispatch event.
# It can be used to run specific tasks on demand.
# The workflow can be triggered from the GitHub Actions tab in the repository.  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: testing code
        run: echo "This is a test step"
      

       

        # This step runs a simple echo command to demonstrate the workflow.
        # You can replace this with any command or script you want to execute.