name: githubcicd
on: workflow_dispatch
# This workflow is triggered by a manual dispatch event.
# It can be used to run specific tasks on demand.
# The workflow can be triggered from the GitHub Actions tab in the repository.  
jobs:
  testing:
    runs-on: ubuntu-latest

    env: 
        SONAR_SCANNER_OPTS: "-Xmx1024m"  # Increase heap size to 1GB

    steps:
      - name: code check out
        uses: actions/checkout@v4

      - name: testing code
        run: mvn test

      - name: checkstyle code
        run: mvn checkstyle:checkstyle
        # This step checks out the repository code so that it can be used in subsequent steps.      
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '11'

      # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7


        
      - name: SonarCloud Scan
        run: sonar-scanner
           -Dsonar.host.url=${{ secrets.SONAR_URL }}
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
           -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
           -Dsonar.sources=src/
           -Dsonar.junit.reportsPath=target/surefire-reports/ 
           -Dsonar.jacoco.reportsPath=target/jacoco.exec 
           -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
           -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/


      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }} #OPTIONAL