name: githubcicd
on: workflow_dispatch
# This workflow is triggered by a manual dispatch event.
# It can be used to run specific tasks on demand.
# The workflow can be triggered from the GitHub Actions tab in the repository.  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: code check out
        uses: actions/checkout@v4

      - name: testing code
        run: mvn test

      - name: checkstyle code
        run: mvn checkstyle:checkstyle
        # This step checks out the repository code so that it can be used in subsequent steps.      
      - name: Java installation
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: setup sonar Qube
        uses: warchant/setup-sonar-scanner@v7
        
      - name: SonarCloud Scan
        run: sonar-scanner
           -Dsonar.host.url=${{ secrets.SONAR_URL }}
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
           -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
           -Dsonar.sources=src/
           -Dsonar.junit.reportsPath=target/surefire-reports/ 
           -Dsonar.jacoco.reportsPath=target/jacoco.exec 
           -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
           -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/