name: githubcicd
on: workflow_dispatch
# This workflow is triggered by a manual dispatch event.
# It can be used to run specific tasks on demand.
# The workflow can be triggered from the GitHub Actions tab in the repository.  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: testing code
        run: echo "This is a test run"
      
