name: testing the action
on: workflow_dispatch
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: testing workflow
        run: echo "running and executed the test workflow successfully"
    
    
